---
title:  "Default values, throwing functions, and checkpoint 4"
excerpt: "1oo Days Of SwiftUI: Day8"

categories:
  - Swift
tags:
  - Swift
last_modified_at: 2024-08-19T14:40:02-05:00
---

# Default values
```swift
func printTimesTables(for number: Int, end: Int = 12) {
    for i in 1...end {
        print("\(i) x \(number) is \(i * number)")
    }
}

printTimesTables(for: 5, end: 20)
printTimesTables(for: 8)
```
- 매개변수에 'default'값을 지정하면 함수를 호출 할 때 매개변수 값을 지정하지 않아도 자동으로 'default'값이 사용된다.

```swift
characters.removeAll(keepingCapacity: true)
```
- 'removeAll'은 기본값이 'false'여서 함수가 사용되는 즉시 배열의 요소가 제거되고 할당된 메모리가 해제된다.
- 하지만 'true'로 지정하면 배열의 모든 요소는 제거되지만 할당된 메모리는 해제되지 않는다.

# Throwing functions

**Error**를 다루는 방법을 알려준다. 예를 들어 읽으려는 파일이 존재하지 않거나 네트워크가 다운되었을 때와 같은 상황을 잘 처리할 수 있는 것이 'throw'이다.

**1. Define the possible errors**
```swift
enum PasswordError: Error {
    case short, obvious
}
```
**2. Write a function that will trigger one of those errors**
```swift
func checkPassword(_ password: String) throws -> String {
    if password.count < 5 {
        throw PasswordError.short
    }

    if password == "12345" {
        throw PasswordError.obvious
    }

    if password.count < 8 {
        return "OK"
    } else if password.count < 10 {
        return "Good"
    } else {
        return "Excellent"
    }
}
```
- 비밀번호가 5자 미만이면 'PasswordError.short'를, 비밀번호가 '12345'와 같으면 'PasswordError.obvous'오류를 발생시키고 함수를 종료한다.



**3. Run the function and handle any errors that might happen**
```swift
let string = "12345"

do {// when using try, we need to be inside a do block
    let result = try checkPassword(string)
    print("Password rating: \(result)")
} catch PasswordError.short {
    print("Please use a longer password.")
} catch PasswordError.obvious {
    print("I have the same combination on my luggage!")
} catch {
    print("There was an error.")
}
```
- 'do' 안에서 'try'를 사용해서 발생 오류가 발생 할 수도 있는 함수를 호출하고 오류가 발생하면 해당하는 'catch' 부분으로 이동하여 오류를 처리한다.

# Checkpoint 4
1. You can’t use Swift’s built-in sqrt() function or similar – you need to find the square root yourself.
2. If the number is less than 1 or greater than 10,000 you should throw an “out of bounds” error.
3. You should only consider integer square roots – don’t worry about the square root of 3 being 1.732, for example.
4. If you can’t find the square root, throw a “no root” error.
<br><br>

```swift
enum bounds : Error {
    case OutOfBounds, noroot
}
func squares(of input: Int) throws -> Int{
    if input > 10000 || input < 1 {throw bounds.OutOfBounds}
    for i in 1...100{
        if i*i == input{
            return i
        }
    }
    throw bounds.noroot
}

do{
    let result = try squares(of: 25)
    print("Square root is \(result).")
} catch bounds.OutOfBounds{
    print("Input is out of Bounds.")
} catch bounds.noroot{
    print("No integer square root found.")
}catch {
    print("An unexpectd error occured")
}
```